remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: unknown flowers
description: "orz"
markdown: kramdown
categories: [post]
defaults:
  -
    scope:
      path: flowers/post
    values:
      layout: post
      mathjax: true
      category: post
